### ISSUE TITLE
Flexibility and performances

### ISSUE THREAD

**Issue by vadmbertr** [meom-group/WideTrax#3]
Hi,

I think the some functions (`fill_nan`, `retrieve_segments`, `plot_psd`) could be more flexible:
- allow to fill nan or compute the PSD for different variables than only `mdt + ssha` by adding a parameter specifying the name of the targeted variable (functions `fill_nan`, `retrieve_segments`),
- allow to plot more than 2 PSD (with custom labels) and allow for unit to be different that $m^2$ (function `plot_psd`).

I also believe that some performance improvements could be achieved by using a `ProcessPoolExecutor` to parallelize the retrieval of segments (`retrieve_segments`) and the computation of the PSD (`calculate_psd`).

I also have a PR ready, let me know what you think!

Vadim

**Comment by Amine-ouhechou** [comment]
Hi,

Thanks for the suggestion! Go ahead and open the PR.

Appreciate your help !
